spring.application.name=bookstore

#h2 database configuration, # is the comment sign in .html, xml <!--com-->, .java//

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

# show generated sql
spring.jpa.show-sql=true